#-------------------------------
# General Site Settings

title: Danny Hollman
logo: 
author: Danny Hollman
description: this is meta description
email: dannyhollman@gmail.com
address: Middletown, CT
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Danny <br> Game Developer

social:
- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "#"}
- {icon: "ti-dribbble", link: "#"}
- {icon: "ti-twitter", link: "https://twitter.com/danny_hollman"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  I'm a software engineer with a focus of AR/VR and game development. I studied full stack software engineering at Holberton School and I'm currently specializing in AR/VR. I'm passionate about creating compelling augmented and virtual reality experiences and helping to solve problems that will push these new technologies further!

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Unity, color: '#fdb157', value: '90%'}
- {name: C#, color: '#9473e6', value: '80%'}
- {name: AR/VR, color: '#bdecf6', value: '80%'}
- {name: Game Development, color: '#ffbcaa', value: '90%'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Software Engineer, date: '2019', organization: 'Holberton School of Software Engineering'}
- {name: AR/VR Specialization, date: '2020', organization: 'Holberton School of Software Engineering'}


#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/vr_room.PNG"
    url: "https://github.com/dannyhollman/VR_Escape_Room"
    
  - image : "assets/images/portfolio/bowman2.PNG"
    url: "https://github.com/dannyhollman/Bowman"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "AR/VR",
    type : "AR/VR"
  }
- {
    title : "Game Development",
    type : "Game Development"
  }
- {
    title : "Hackathon",
    type : "Hackathon"
  }

portfolio-items:
  - image : "assets/images/portfolio/vr_room.PN"
    url: "https://github.com/dannyhollman/VR_Escape_Room"
    portfolio-type:
     - type: "AR/VR"
     - type: "Game Development"
      
  - image : "assets/images/portfolio/bowman2.PNG"
    url: "https://github.com/dannyhollman/Bowman"
    portfolio-type:
      - type: "Game Development"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: dannyhollman@gmail.com
